Models/ErrorViewModel.cs
namespace Workout_Logger.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Workout.cs
namespace Workout_Logger.Models
{
    public class Workout
    {
        public int Id { get; set; }
        public string Activity { get; set; }
        public string Duration { get; set; }
        public int Calories { get; set; }
        public DateTime Date { get; set; }
        public Workout()
        {
            
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Workout_Logger.Models;

namespace Workout_Logger.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/WorkoutsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Workout_Logger.Data;
using Workout_Logger.Models;

namespace Workout_Logger.Controllers
{
    public class WorkoutsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WorkoutsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Workouts
        public async Task<IActionResult> Index()
        {
              return _context.Workout != null ? 
                          View(await _context.Workout.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Workout'  is null.");
        }

        // GET: Workouts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Workout == null)
            {
                return NotFound();
            }

            var workout = await _context.Workout
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workout == null)
            {
                return NotFound();
            }

            return View(workout);
        }

        // GET: Workouts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Workouts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Activity,Duration,Calories,Date")] Workout workout)
        {
            if (ModelState.IsValid)
            {
                _context.Add(workout);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(workout);
        }

        // GET: Workouts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Workout == null)
            {
                return NotFound();
            }

            var workout = await _context.Workout.FindAsync(id);
            if (workout == null)
            {
                return NotFound();
            }
            return View(workout);
        }

        // POST: Workouts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Activity,Duration,Calories,Date")] Workout workout)
        {
            if (id != workout.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(workout);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkoutExists(workout.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(workout);
        }

        // GET: Workouts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Workout == null)
            {
                return NotFound();
            }

            var workout = await _context.Workout
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workout == null)
            {
                return NotFound();
            }

            return View(workout);
        }

        // POST: Workouts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Workout == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Workout'  is null.");
            }
            var workout = await _context.Workout.FindAsync(id);
            if (workout != null)
            {
                _context.Workout.Remove(workout);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkoutExists(int id)
        {
          return (_context.Workout?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<section id="header-banner" class="jumbotron jumbotron-fluid bg-primary text-white text-center mb-0">
    <div class="container">
        <h1>Welcome to Workout Log</h1>
        <p>Your personal fitness journey starts here!</p>
    </div>
</section>

<section id="get-started" class="container mt-4">
    <h2>Getting Started Today!</h2>
    <p>Ready to embark on your fitness journey? Join us and start tracking your workouts with ease. Your goals, our technology – a perfect match!</p>
</section>

<section id="about-creator" class="container mt-4">
    <h2>About the Creator</h2>
    <p>Hi there, I'm Miguel, the passionate developer behind Workout Log. With a love for fitness and technology, I've created this platform to help you seamlessly track your workouts and achieve your goals.</p>
</section>

<section id="updates" class="container mt-4">
    <h2>Latest Updates</h2>
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">Release 1.0: Project creation</h3>
            <ul>
                <li>Introducing MVC design patterns for better organization.</li>
                <li>Enhanced security with login and registration authentication.</li>
                <li>Leveraged the power of SQL database for efficient data management.</li>
            </ul>
        </div>
    </div>
    <div class="card mt-3">
        <div class="card-body">
            <h3 class="card-title">Release 1.1: Coming Soon!</h3>
            <ul>
                <li>Added more details to workouts, including date and time.</li>
                <li>Edit entered workouts for accurate tracking.</li>
                <li>Delete unwanted workouts with ease.</li>
                <li>Enhanced UI for a more user-friendly experience.</li>
            </ul>
        </div>
    </div>
</section>

<section id="technologies-used" class="container mt-4">
    <h2>Featured Technologies</h2>
    <ul>
        <li>ASP.NET for seamless application development.</li>
        <li>MVC Design Patterns for a clean and organized codebase.</li>
        <li>CSS and Bootstrap classes for personalized UI customization.</li>
        <li>Secure Login and Registration Authentication for data protection.</li>
        <li>SQL Database to efficiently store and manage workout data.</li>
    </ul>
</section>

<section id="follow-on-github" class="container mt-4">
    <h2>Stay Updated! Follow us on GitHub</h2>
    <p>Don't miss out on the latest updates and enhancements. Follow the project on GitHub to track its progress and get notified about new features.</p>
    <a href="https://github.com/Miguel619/WorkoutLogs" target="_blank" class="btn btn-primary">Follow on GitHub</a>
</section>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Workout_Logger</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Workout_Logger.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Workout_Logger</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Workouts" asp-action="Index">Workouts</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Workout_Logger - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Workouts/Create.cshtml
@model Workout_Logger.Models.Workout

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Workout</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Activity" class="control-label"></label>
                <input asp-for="Activity" class="form-control" />
                <span asp-validation-for="Activity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Calories" class="control-label"></label>
                <input asp-for="Calories" class="form-control" />
                <span asp-validation-for="Calories" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Workouts/Delete.cshtml
@model Workout_Logger.Models.Workout

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Workout</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Activity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Calories)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Calories)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Workouts/Details.cshtml
@model Workout_Logger.Models.Workout

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Workout</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Activity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Calories)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Calories)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Workouts/Edit.cshtml
@model Workout_Logger.Models.Workout

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Workout</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Activity" class="control-label"></label>
                <input asp-for="Activity" class="form-control" />
                <span asp-validation-for="Activity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Calories" class="control-label"></label>
                <input asp-for="Calories" class="form-control" />
                <span asp-validation-for="Calories" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Workouts/Index.cshtml
@model IEnumerable<Workout_Logger.Models.Workout>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Activity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Calories)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Activity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Calories)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>